display_name: Bettbox

packager: appshub
packagerEmail: appshubcc@gmail.com
license: Other

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

keywords:
  - Bettbox
  - Clash
  - ClashMeta
  - Proxy

generic_name: Bettbox

group: Applications/Internet

startup_notify: true

install: |
  mkdir -p %{buildroot}%{_bindir}
  mkdir -p %{buildroot}%{_datadir}/%{name}
  mkdir -p %{buildroot}%{_datadir}/applications
  mkdir -p %{buildroot}%{_datadir}/pixmaps
  mkdir -p %{buildroot}%{_datadir}/icons/hicolor/symbolic/apps
  cp -r %{name}/* %{buildroot}%{_datadir}/%{name}
  ln -s %{_datadir}/%{name}/%{name} %{buildroot}%{_bindir}/%{name}
  cp -r %{name}.desktop %{buildroot}%{_datadir}/applications
  cp -r %{name}.png %{buildroot}%{_datadir}/pixmaps
  cp -r %{buildroot}%{_datadir}/%{name}/data/flutter_assets/assets/images/icon_monochrome.svg %{buildroot}%{_datadir}/icons/hicolor/symbolic/apps/bettbox-symbolic.svg
  update-mime-database %{_datadir}/mime &> /dev/null || :

files: |
  %defattr(-,root,root)
  %attr(4755, root, root) %{_datadir}/%{name}/BettboxCore
  %{_bindir}/%{name}
  %{_datadir}/%{name}
  %{_datadir}/applications/%{name}.desktop
  %{_datadir}/pixmaps/%{name}.png
  %{_datadir}/icons/hicolor/symbolic/apps

attr: |
  %attr(4755, root, root) %{_datadir}/%{name}/BettboxCore