display_name: Bettbox

icon: ./assets/images/icon.png
icons_symbolic:
  - name: bettbox-symbolic
    source: ./assets/images/icon_monochrome.svg

keywords:
  - Bettbox
  - Clash
  - ClashMeta
  - Proxy

generic_name: Bettbox

categories:
  - Network

startup_notify: true

include: []